---
cisco_intersight:
  key_id: 5ed10e437564612d3352cc2d/606616ad7564612d3042cdd0/6205497b7564612d301e04c8
  secret_key: |-
    -----BEGIN EC PRIVATE KEY-----
    MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgC4s6itMGuC+Q4zH+
    WpsJwg1NlFEhEaLYYZdFQ9gvJXGhRANCAARWYtq4hw0wHV4QTBgcQhIay6ant5k0
    MzfSgM/rZfuMHCy5cDnqFkFjra3WQ5x1Z2XmN5GlMzEGt60weQ6Kbo3R
    -----END EC PRIVATE KEY-----
