---
test:
  cisco_intersight_defaults: &cisco_intersight_defaults
    cisco_intersight_username: username
    cisco_intersight_password: password
  cisco_intersight:
    <<: *cisco_intersight_defaults
