---
test:
  cisco_intersight_defaults: &cisco_intersight_defaults
    key_id: "5ed10e437564612d3352cc2d/606616ad7564612d3042cdd0/6205497b7564612d301e04c8"
    secret_key: "-----BEGIN EC PRIVATE KEY-----\nMIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgC4s6itMGuC+Q4zH+\nWpsJwg1NlFEhEaLYYZdFQ9gvJXGhRANCAARWYtq4hw0wHV4QTBgcQhIay6ant5k0\nMzfSgM/rZfuMHCy5cDnqFkFjra3WQ5x1Z2XmN5GlMzEGt60weQ6Kbo3R\n-----END EC PRIVATE KEY-----"
  cisco_intersight:
    <<: *cisco_intersight_defaults
